### ISSUE TITLE
graphics.Font() CharacterWidth method not recognised

### ISSUE THREAD

**Issue by sityware** [ty-porter/RGBMatrixEmulator#10]
Hi,

My code uses the below CharacterWidth method from the graphics.Font Class of the library.

```
font_change = graphics.Font()
font_change.LoadFont('fonts/6x10.bdf')
change_width = sum([font_change.CharacterWidth(ord(c)) for c in asset['

```
I get the error
`AttributeError: 'Font' object has no attribute 'CharacterWidth'`

Can the method be emulated?
https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/bindings/python/rgbmatrix/graphics.pyx

Many thanks.

**Comment by ty-porter** [comment]
This should be fixed in version 0.4.1, the package is already released to pypi and source code should be merged shortly. 

Feel free to add any issues you may have here.
