### ISSUE TITLE
Some examples please?

### ISSUE THREAD

**Issue by berlingozzo** [ty-porter/RGBMatrixEmulator#18]
Hello - thanks for this repository. I'm coming from Adafruit'x NeoPixel and GFX libraries and I'd like to use your RGBMatrix libraries, but I'm finding it difficult to start without examples.

Could you please post the code corresponding to the sample screenshots / gifs?

thanks

**Comment by ty-porter** [comment]
Hi!

This is simply an emulator for the existing [rpi-rgb-led-matrix library](https://github.com/hzeller/rpi-rgb-led-matrix), so if you have questions about how it works or how to begin development for it, I'd start there.

With that said, that library does include sample files that you could install the emulator into according to instructions in the README: https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/bindings/python/samples

I also have some projects with the emulator pre-installed:
https://github.com/ty-porter/mlb-led-scoreboard-emulated
https://github.com/ty-porter/nfl-led-scoreboard-emulated

The emulator is also compatible with other projects such as https://github.com/riffnshred/nhl-led-scoreboard

**Comment by ty-porter** [comment]
Thanks for the suggestion, I just needed time to get the samples together, working, and documented.
