### ISSUE TITLE
Request to include Font.height from graphics module?

### ISSUE THREAD

**Issue by sityware** [ty-porter/RGBMatrixEmulator#19]
Hi,

My script uses the height method from graphics Font class.

    // Return height of font in pixels. Returns -1 if font has not been loaded.
    int height() const { return font_height_; }`

In the main library, it returns a value where it looks to be a @property in the emulator?
    @property
    def height(self):

**Comment by ty-porter** [comment]
Hi, 

The `@property` decorator is used to define a getter method for the `height` attribute to match the Python implementation of the `rpi-rgb-led-matrix` library.

Example:

```python
# Correct behavior
font.height

# instead of 
font.height()
```

The return value should be an integer as expected. Feel free to open another issue if you find it doesn't behave to spec.

https://docs.python.org/3/library/functions.html#property
