### ISSUE TITLE
pygame dependency install issues

### ISSUE THREAD

**Issue by twfarley** [ty-porter/RGBMatrixEmulator#30]
`$ python3 -m pip  install RGBMatrixEmulator
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting RGBMatrixEmulator
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.6.0-py3-none-any.whl (46 kB)
Collecting bdfparser<=2.2.0
  Using cached https://www.piwheels.org/simple/bdfparser/bdfparser-2.2.0-py3-none-any.whl (12 kB)
Collecting scikit-image<=0.18.1
  Downloading scikit-image-0.18.1.tar.gz (29.7 MB)
     |████████████████████████████████| 29.7 MB 31 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting tornado>=6.1
  Downloading tornado-6.1-cp39-cp39-manylinux2014_aarch64.whl (427 kB)
     |████████████████████████████████| 427 kB 624 kB/s 
Collecting pygame<=2.0.1
  Using cached pygame-2.0.1.tar.gz (5.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_x4d8gc4
         cwd: /tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/buildconfig/config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "/tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/buildconfig/config_unix.py", line 194, in main
        DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
      File "/tmp/pip-install-zypxna2y/pygame_68fde1c9790044f1bac5c5abc9c0c5c3/buildconfig/config_unix.py", line 39, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range
    
    Hunting dependencies...
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c7/b8/06e02c7cca7aec915839927a9aa19f749ac17a3d2bb2610b945d2de0aa96/pygame-2.0.1.tar.gz#sha256=8b1e7b63f47aafcdd8849933b206778747ef1802bd3d526aca45ed77141e4001 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-2.0.0.tar.gz (5.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d8wdn7kj
         cwd: /tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/
    Complete output (29 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    /bin/sh: 1: sdl2-config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/buildconfig/config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "/tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/buildconfig/config_unix.py", line 194, in main
        DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
      File "/tmp/pip-install-zypxna2y/pygame_d6e1011815ab4325ba7df8289e20d2d5/buildconfig/config_unix.py", line 39, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range
    
    Hunting dependencies...
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/Compilation
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/0c/d164411381bada8feae57359aa9296defbed3035f4b55bef6a271cb0573c/pygame-2.0.0.tar.gz#sha256=63b038da116a643046181b02173fd894d87d2f85ecfd6aa7d5ece73c6ef501e9 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_6294f82446db4f72974571bd9a6bffeb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_6294f82446db4f72974571bd9a6bffeb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_iofft48
         cwd: /tmp/pip-install-zypxna2y/pygame_6294f82446db4f72974571bd9a6bffeb/
    Complete output (12 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz#sha256=301c6428c0880ecd4a9e3951b80e539c33863b6ff356a443db1758de4f297957 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.5.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_d4c0df05c8ff448ab3d3dfb64bd392ae/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_d4c0df05c8ff448ab3d3dfb64bd392ae/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5beq6bue
         cwd: /tmp/pip-install-zypxna2y/pygame_d4c0df05c8ff448ab3d3dfb64bd392ae/
    Complete output (12 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/4f/b3a521bb4db6ef696bcffca58b833aa2e84f7e7c142951d506d840ced57a/pygame-1.9.5.tar.gz#sha256=d15e7238015095a12c19379565a66285e989fdcb3807ec360b27338cd8bdaf05 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.4.tar.gz (4.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_a3e999ec36bc4ca9a22fba2ca7ae4aaa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_a3e999ec36bc4ca9a22fba2ca7ae4aaa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yl6z943m
         cwd: /tmp/pip-install-zypxna2y/pygame_a3e999ec36bc4ca9a22fba2ca7ae4aaa/
    Complete output (12 lines):
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b2/6b/c510f0853765eb2219ca5aa3d416d65bb0dea7cd9bb2984aea0a0e04c24d/pygame-1.9.4.tar.gz#sha256=700d1781c999af25d11bfd1f3e158ebb660f72ebccb2040ecafe5069d0b2c0b6 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.3.tar.gz (3.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_66ca307710814918ad22a5162f322080/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_66ca307710814918ad22a5162f322080/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uu3igxi9
         cwd: /tmp/pip-install-zypxna2y/pygame_66ca307710814918ad22a5162f322080/
    Complete output (16 lines):
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "freetype-config" failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/61/06/3c25051549c252cc6fde01c8aeae90b96831370884504fe428a623316def/pygame-1.9.3.tar.gz#sha256=751021819bdc0cbe5cbd51904abb6ff9e9aee5b0e8955af02284d0e77d6c9ec2 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.2.tar.gz (3.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/pygame_30d63c1767bd4a63b42ab4c9e4b9d890/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/pygame_30d63c1767bd4a63b42ab4c9e4b9d890/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7p7taqy0
         cwd: /tmp/pip-install-zypxna2y/pygame_30d63c1767bd4a63b42ab4c9e4b9d890/
    Complete output (16 lines):
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: sdl-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    /bin/sh: 1: freetype-config: not found
    Unable to run "sdl-config". Please make sure a development version of SDL is installed.
    
    Hunting dependencies...
    WARNING: "sdl-config" failed!
    WARNING: "freetype-config" failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/da/b8/b110cdea95452f8f9f9e79d02062fdccaebfd808a667d6d9a805ca8d222a/pygame-1.9.2.tar.gz#sha256=2050c68ff6eba1f801efc14fd1f805aaa3a94936c80ed6725b64a75ca1bce66f (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting RGBMatrixEmulator
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.5.4-py3-none-any.whl (33 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.5.3-py3-none-any.whl (33 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.5.2-py3-none-any.whl (33 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.5.1-py3-none-any.whl (33 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.5.0-py3-none-any.whl (33 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.4.3-py3-none-any.whl (29 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.4.2-py3-none-any.whl (29 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.4.1-py3-none-any.whl (29 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.4.0-py3-none-any.whl (29 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.3.1-py3-none-any.whl (29 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.3.0-py3-none-any.whl (29 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.2.3-py3-none-any.whl (28 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.2.1-py3-none-any.whl (6.2 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.2.0-py3-none-any.whl (6.2 kB)
  Using cached https://www.piwheels.org/simple/rgbmatrixemulator/RGBMatrixEmulator-0.1.1-py3-none-any.whl (5.7 kB)
Collecting bresenham==0.2.1
  Downloading bresenham-0.2.1-py3-none-any.whl (3.7 kB)
Collecting RGBMatrixEmulator
  Using cached RGBMatrixEmulator-0.1.0.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zypxna2y/rgbmatrixemulator_af444e44ae9a47fca05643c56752ed2c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zypxna2y/rgbmatrixemulator_af444e44ae9a47fca05643c56752ed2c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4gaxtan3
         cwd: /tmp/pip-install-zypxna2y/rgbmatrixemulator_af444e44ae9a47fca05643c56752ed2c/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zypxna2y/rgbmatrixemulator_af444e44ae9a47fca05643c56752ed2c/setup.py", line 10, in <module>
        with open("description.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'description.md'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/20/47/fa5ce85ae863caf3191f9464495cbd059b0e24dbb480e95e3e25a78b9823/RGBMatrixEmulator-0.1.0.tar.gz#sha256=755b6aa2c238006a5f0ab21f5ee7584e368cda1fd4c1395808c1f6c672a76f74 (from https://pypi.org/simple/rgbmatrixemulator/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install rgbmatrixemulator==0.1.1, rgbmatrixemulator==0.2.0, rgbmatrixemulator==0.2.1, rgbmatrixemulator==0.2.3, rgbmatrixemulator==0.3.0, rgbmatrixemulator==0.3.1, rgbmatrixemulator==0.4.0, rgbmatrixemulator==0.4.1, rgbmatrixemulator==0.4.2, rgbmatrixemulator==0.4.3, rgbmatrixemulator==0.5.0, rgbmatrixemulator==0.5.1, rgbmatrixemulator==0.5.2, rgbmatrixemulator==0.5.3, rgbmatrixemulator==0.5.4 and rgbmatrixemulator==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    rgbmatrixemulator 0.6.0 depends on pygame<=2.0.1
    rgbmatrixemulator 0.5.4 depends on pygame<=2.0.1
    rgbmatrixemulator 0.5.3 depends on pygame<=2.0.1
    rgbmatrixemulator 0.5.2 depends on pygame<=2.0.1
    rgbmatrixemulator 0.5.1 depends on pygame<=2.0.1
    rgbmatrixemulator 0.5.0 depends on pygame<=2.0.1
    rgbmatrixemulator 0.4.3 depends on pygame<=2.0.1
    rgbmatrixemulator 0.4.2 depends on pygame<=2.0.1
    rgbmatrixemulator 0.4.1 depends on pygame<=2.0.1
    rgbmatrixemulator 0.4.0 depends on pygame<=2.0.1
    rgbmatrixemulator 0.3.1 depends on pygame<=1.9.6
    rgbmatrixemulator 0.3.0 depends on pygame<=1.9.6
    rgbmatrixemulator 0.2.3 depends on pygame<=1.9.6
    rgbmatrixemulator 0.2.1 depends on pygame<=1.9.6
    rgbmatrixemulator 0.2.0 depends on pygame<=1.9.6
    rgbmatrixemulator 0.1.1 depends on pygame<=1.9.6

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

**Comment by ty-porter** [comment]
Pretty sure this is caused by a Python version compatibility issue with Pygame. I got a similar error trying to install it under Python 3.10.

If this doesn't fix, feel free to reopen and I'll take another look.
