### ISSUE TITLE
Proposal: a sixel adapter for  better terminal-only experience

### ISSUE THREAD

**Issue by prashnts** [ty-porter/RGBMatrixEmulator#50]
Hi! Thanks for this library, the browser adapter is really useful.

If you're interested I am willing to contribute a sixel based adapter which renders the images in terminal. I have it implemented in my LED matrix project [here](https://github.com/prashnts/disinfo/blob/master/disp_info/renderers/sixel.py), but currently only tested in macOS.

Currently it looks like this:

<img width="1172" alt="Screenshot 2023-06-09 at 19 09 24" src="https://github.com/ty-porter/RGBMatrixEmulator/assets/5663391/1f969ce0-0dc3-44b5-9c75-64b6bcfeac83">

Note that it's not particularly performant and only supported in a few terminal emulators like iTerm, but I think it is useful for when you don't want to switch to browser window.

**Comment by ty-porter** [comment]
I think this looks great, and would definitely welcome this contribution.
