### ISSUE TITLE
Consider using 'parallel' in hardware settings

### ISSUE THREAD

**Issue by quantumspaces** [ty-porter/RGBMatrixEmulator#6]
Hi, love the emu and the thing has helped a lot in my development.

Here's a small observation: I emulate matrices with one channel, and sometimes 2 channels in parallel. The parallel hardware setting seems to be ignored.

For example: a matrix of a total of 64x64 pixels, in 2 parallel channels (2 pcs of 64x32 panels) requires a setting as such:

    width: 64
    height: 32
    parallel: 2
    ....

However, in emulator , the parallel setting seems to be ignored, and I need a setting as shown below.

    width: 64
    height: 64
    parallel: 1 
    # parallel 1 or 2 doesn't seem to affect the emulator
    ....

My workaround is very simple. In my code, whenever I launch the emulator instead of running on a connected hardware (PI), I simply multiply height by the value in 'parallel'.

Thanks for a great lib. Thought you would be interested.

**Comment by ty-porter** [comment]
Thanks for the suggestion, this is a really good idea that I had overlooked. This has just been released for 0.4.0 along with the requested changes for #7 as well.

**Comment by quantumspaces** [comment]
Thanks for this! Awesome. I appreciate all the updates. Will try tonight with new settings :)
