### ISSUE TITLE
With 0.11.0 the right half of display in 64x32 configuration is blank

### ISSUE THREAD

**Issue by jdesai61** [ty-porter/RGBMatrixEmulator#62]
I am trying to run https://github.com/MLB-LED-Scoreboard using emulator.
When I try 
```
python3 main.py --emulated --led-rows 32 --led-cols 64

```
In both cases, the configuration or anything else isn't changed - except changing emulator version using pip.
```
{
    "pixel_outline": 0,
    "pixel_size": 16,
    "pixel_style": "square",
    "display_adapter": "browser",
    "suppress_font_warnings": false,
    "suppress_adapter_load_errors": false,
    "browser": {
        "_comment": "For use with the browser adapter only.",
        "port": 8888,
        "target_fps": 24,
        "fps_display": false,
        "quality": 70,
        "image_border": true,
        "debug_text": false,
        "image_format": "JPEG"
    },
    "log_level": "info"
}

```
With 0.11.0 release, right half of display is blank.  But with 0.10.0, is looks fine. See attached.
![Screenshot 2024-02-23 105112](https://github.com/ty-porter/RGBMatrixEmulator/assets/12818520/dbe775e9-814c-4dc4-aaa6-865a345b5ef0)
![Screenshot 2024-02-23 105013](https://github.com/ty-porter/RGBMatrixEmulator/assets/12818520/f31597a4-e67d-4fa9-a0c5-9796a37aaa3e)

What is strange is that even though 0.10.0 debug display shows 32x32 matrix size and image size 512x512, it actually displays 1024x512 image as expected. Whereas, 0.11.0 debug displays shows 64x32 matrix size and image size 1024x512, it actually displays 512x512 image.

**Comment by ty-porter** [comment]
I pushed v0.11.1 with a fix for this. We recently re-wrote the rendering code and row/column values accidentally got swapped.

**Comment by jdesai61** [comment]
Just pulled 0.11.1 and it looks good. Thanks

**Comment by jdesai61** [comment]
Now that I am testing this some more, the current implementation meets certain application requirements - where the image is being periodically updated by tidbyt and doesn't change between pulls.   

However, what I am realizing is that typical tidbyt apps (running on server or community apps here:  ) don't just create a static webp image. They actually create an animated webp image. So for example a digital clock may generate a single webp image with animated frames for a full minute.  Then tidbyt may pull image over HTTP every minute (or some other interval). A scrolling text for example is sent in one webp image with animated frames.   

The animation interval and # of frame in each webp image is decided by the application, so not sure how to achieve similar results in the emulator context.
