### ISSUE TITLE
Tkinter Icon Fix Suggestion

### ISSUE THREAD

**Issue by Iainrach** [ty-porter/RGBMatrixEmulator#67]
Gosh I love this Library !

Worked perfectly with Terminal & Pygame but gave the 'not defined' error below with Tkinter, which I have simulated with a few lines of code.

from tkinter import *
root = Tk()

root.iconbitmap('/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator/icon.ico')
#imgicon = PhotoImage(file='/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator/icon.gif')
#root.tk.call('wm', 'iconphoto', root._w, imgicon)  

root.mainloop()

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator/icon.ico" not defined
>>> 

Found this :-

https://stackoverflow.com/questions/18537918/why-isnt-ico-file-defined-when-setting-windows-icon

from tkinter import *
root = Tk()

#root.iconbitmap('/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator/icon.ico')
imgicon = PhotoImage(file='/usr/local/lib/python3.9/dist-packages/RGBMatrixEmulator/icon.gif')
root.tk.call('wm', 'iconphoto', root._w, imgicon)  

root.mainloop()

& Success !

Hopefully this may be of some help ?

**Comment by ty-porter** [comment]
Should be resolved in v0.11.3. Please re-open if you see anything else. Thanks for the report.
